# Generated by Django 4.2.6 on 2023-11-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee_models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_no", models.IntegerField()),
                ("emp_name", models.CharField(max_length=20)),
                ("emp_salary", models.IntegerField()),
                ("emp_address", models.TextField()),
            ],
        ),
    ]
